# Generated by Django 4.0.5 on 2022-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet',
            field=models.FileField(upload_to='uploads/sheets'),
        ),
    ]
